# Generated by Django 3.1.7 on 2021-04-01 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Cell_Number', models.CharField(max_length=10)),
                ('Surbub', models.CharField(choices=[('Kuyasa', 'Kuyasa'), ('Harare', 'Harare'), ('Makhaza', 'Makhaza'), ('Site B', 'Site B'), ('Site C', 'Site C'), ('kraaifontain', 'Kraaifontain')], max_length=200)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Admin', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Last_Name', 'First_Name')},
            },
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Deceased', models.DateTimeField(auto_now_add=True, null=True)),
                ('Name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='deceased_name_set', to='webapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='webapp.member')),
                ('deceased', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.deceased')),
            ],
            options={
                'unique_together': {('deceased', 'Name')},
            },
        ),
    ]
