# Generated by Django 3.2 on 2021-04-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='member',
            name='Admin',
        ),
    ]
