# Generated by Django 3.2 on 2021-04-23 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_alter_contributions_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributions',
            options={'ordering': ('-Date',)},
        ),
        migrations.RenameField(
            model_name='contributions',
            old_name='name',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='member',
            name='admin',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contributions',
            unique_together={('deceased', 'member')},
        ),
    ]
